### ISSUE TITLE
Proposed feature: extend LambdaResource to include framework-specific metadata

### ISSUE THREAD

**Issue by rogerchi** [ServerlessLife/lambda-live-debugger#59]
Depending on the length of the stack name, sometimes our lambda function names do not include personal stack identifiers, so it is hard to filter the foundLambdas.  My proposal would be to extend the `LambdaResource` type to include framework specific metadata, such as `stackName` in the `foundLambdas` array so that we can filter more easily.  I can try to make a PR for this if you think the idea is reasonable.

**Comment by ServerlessLife** [comment]
That is a great idea, and it would be easy to implement.

It would be great if you did it. If not, I will do it over the weekend. I suggest a parameter named `stack` with an option to use wildcard (`*`) like the `function` parameter.

**Comment by ServerlessLife** [comment]
I understand now 😃. You would use that data in `lldebugger.config.ts` -> `getLambdas` method.

I apologize. :pray: It was a long day. I should read your message thoroughly.

That would be really useful. We gather a lot of data while searching for Lambdas, and it is a shame to throw that away if it can be used.
